### ISSUE TITLE
reactivesocket -> rsocket

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-tck#26]
What needs to happen to allow this repo moving to github.com/rsocket/rsocket-tck?

How will moving this affect the Java and C++ projects?

**Comment by xytosis** [comment]
What is the reasoning behind moving this repo?

**Comment by benjchristensen** [comment]
Because we are renaming everything from reactivesocket to rsocket.

**Comment by xytosis** [comment]
You're also merging with the cli repo?

**Comment by benjchristensen** [comment]
Nope. Fixing typo.
