### ISSUE TITLE
RFC: should we consider a more adaptable serialised format like JSON 

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-tck#31]

**Comment by yschimke** [comment]
I'm not sold on 

```
!
name%%fireAndForget2
subscribe%%fnf%%22b84540-f916-4f7f-9211-12e235e30225%%c%%d
request%%1%%22b84540-f916-4f7f-9211-12e235e30225
await%%terminal%%22b84540-f916-4f7f-9211-12e235e30225
assert%%no_error%%22b84540-f916-4f7f-9211-12e235e30225
assert%%completed%%22b84540-f916-4f7f-9211-12e235e30225
!
```

**Comment by yschimke** [comment]
This PR seems to show the problem with evolving the current format

https://github.com/ReactiveSocket/reactivesocket-tck/pull/30/files

With JSON we could at least make this field optional, and only include in tests that need it. Those tests could fail individual runs in cpp, js or java.  Without requiring upgrading all test runners at same time.

**Comment by xytosis** [comment]
I agree, when I made this format it was just for convenience and speed's sake so I could start working on the driver sooner. JSON would be a better choice for the serialization and it shouldn't be too hard to update, the commands could be an ordered list of JSON objects containing the information for the type of command.
